# TAREA 5 - QLEARNING TRES EN RAYA

Aarón Medina Melián

Importación de librerías

In [27]:
import matplotlib.pyplot as plt
import numpy as np

Función que dibuja el tablero dado un estado

In [28]:
# Función para dibujar el tablero a partir de un array de 1D
def dibujar_tablero(array):
    if len(array) != 9:
        print("El array debe tener exactamente 9 elementos.")
        return
    
    tablero = np.array(array).reshape((3, 3))

    plt.figure(figsize=(6, 6))
    plt.imshow(np.ones((3, 3, 3)))
    plt.xticks([]), plt.yticks([])

    for i in range(1, 3):
        plt.plot([i, i], [0, 3], color="black", linewidth=2)
        plt.plot([0, 3], [i, i], color="black", linewidth=2)

    for i in range(3):
        for j in range(3):
            if tablero[i, j] == 1:
                plt.plot(j + 0.5, i + 0.5, 'o', markersize=40, markeredgecolor='blue', markerfacecolor='none')
            elif tablero[i, j] == 2:
                plt.plot(j + 0.5, i + 0.5, 'x', markersize=40, color='red')

    plt.show()


Función que comprueba si es victoria del jugador 1

In [29]:
def es_victoria_jugador1(array):
    # Combinaciones de victoria para el jugador 1 (círculos)
    combinaciones_victoria = [
        [0, 1, 2], [3, 4, 5], [6, 7, 8],  # Filas
        [0, 3, 6], [1, 4, 7], [2, 5, 8],  # Columnas
        [0, 4, 8], [2, 4, 6]              # Diagonales
    ]

    # Verificar cada combinación de victoria
    for combinacion in combinaciones_victoria:
        if all(array[i] == 1 for i in combinacion):
            return True  # Hay una victoria del jugador 1 en esta combinación

    return False  # No hay victoria del jugador 1 en ninguna combinación

Función que comprueba si es victoria del jugador 2

In [30]:
def es_victoria_jugador2(array):
    # Combinaciones de victoria para el jugador 2 (cruces)
    combinaciones_victoria = [
        [0, 1, 2], [3, 4, 5], [6, 7, 8],  # Filas
        [0, 3, 6], [1, 4, 7], [2, 5, 8],  # Columnas
        [0, 4, 8], [2, 4, 6]              # Diagonales
    ]

    # Verificar cada combinación de victoria
    for combinacion in combinaciones_victoria:
        if all(array[i] == 2 for i in combinacion):
            return True  # Hay una victoria del jugador 2 en esta combinación

    return False  # No hay victoria del jugador 2 en ninguna combinación


Función que comprueba si un estado es empate

In [31]:
def es_empate(array):
    # Verificar si no hay celdas vacías (0) en el array
    return all(elem != 0 for elem in array)

Función que comprueba si un estado es válido o no

In [32]:
def es_estado_valido(array):
    # Verificar si el array tiene la longitud correcta (9 elementos)
    if len(array) != 9:
        return False

    # Verificar si cada elemento del array es 0, 1 o 2
    for elem in array:
        if elem not in [0, 1, 2]:
            return False

    # Contar el número de círculos y cruces
    num_circulos = array.count(1)
    num_cruces = array.count(2)

    # Verificar si la diferencia entre el número de círculos y cruces es 0 o 1
    if abs(num_circulos - num_cruces) > 1:
        return False

    # Verificar si el primer movimiento fue realizado por el jugador con el símbolo "1"
    if array.count(1) < array.count(2):
        return False

    return True


Función que calcula el estado desde la representación numérica

In [33]:
def estado_desde_numero(numero):
    if not isinstance(numero, int) or numero < 0 or numero >= 3**9:
        print("Número no válido.")
        return None

    # Convertir el número a una representación ternaria
    ternario = np.base_repr(numero, base=3, padding=9)[-9:]

    # Mapear los dígitos ternarios a los valores del juego (0, 1, 2)
    estado = list(map(int, ternario))

    return estado

Función que calcula la representación numérica de un estado

In [34]:

def numero_desde_estado(estado):
    # Verificar si el estado es una lista de 9 números enteros
    if not isinstance(estado, list) or len(estado) != 9 or not all(isinstance(num, int) for num in estado):
        print("Estado no válido.")
        return None

    # Convertir la lista de dígitos a un número en base 3
    numero = int(''.join(map(str, estado)), 3)

    return numero

Generación de los estados posibles 

In [35]:
estados_posibles = []
estados_valores = []
numero_estados_totales = 0
numero_estados_validos = 0
matriz_recompensas = []

diccionario = {}
diccionaroInverso = {}

for a in range(3):
    for b in range(3):
        for c in range(3):
            for d in range(3):
                for e in range(3):
                    for f in range(3):
                        for g in range(3):
                            for h in range(3):
                                for i in range(3):
                                    estado = [a, b, c, d, e, f, g, h, i]
                                    numero_estados_totales += 1
                                    if (estado.count(2) == estado.count(1)) or (estado.count(1) == (estado.count(2) + 1)):
                                        if not(es_victoria_jugador1(estado) and es_victoria_jugador2(estado)):
                                            valor_estado = 0
                                            for i, j in zip(range(0, 9, 1), range(8, -1, -1)):
                                                valor_estado += 3**i*estado[j]
                                            if es_victoria_jugador1(estado):
                                                matriz_recompensas.append(100)
                                            elif es_victoria_jugador2(estado):
                                                matriz_recompensas.append(-100)
                                            elif es_empate(estado):
                                                matriz_recompensas.append(1)
                                            else:
                                                matriz_recompensas.append(0)
                                            estados_posibles.append(estado)
                                            estados_valores.append(valor_estado)
                                            diccionario[numero_estados_validos] = valor_estado
                                            diccionaroInverso[valor_estado] = numero_estados_validos
                                            numero_estados_validos += 1

                                        
print(estados_posibles)
print(estados_valores)
print("Hay",numero_estados_totales,"estados totales")
print("Hay",numero_estados_validos,"estados válidos")


[[0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, 0, 1, 0], [0, 0, 0, 0, 0, 0, 0, 1, 2], [0, 0, 0, 0, 0, 0, 0, 2, 1], [0, 0, 0, 0, 0, 0, 1, 0, 0], [0, 0, 0, 0, 0, 0, 1, 0, 2], [0, 0, 0, 0, 0, 0, 1, 1, 2], [0, 0, 0, 0, 0, 0, 1, 2, 0], [0, 0, 0, 0, 0, 0, 1, 2, 1], [0, 0, 0, 0, 0, 0, 2, 0, 1], [0, 0, 0, 0, 0, 0, 2, 1, 0], [0, 0, 0, 0, 0, 0, 2, 1, 1], [0, 0, 0, 0, 0, 1, 0, 0, 0], [0, 0, 0, 0, 0, 1, 0, 0, 2], [0, 0, 0, 0, 0, 1, 0, 1, 2], [0, 0, 0, 0, 0, 1, 0, 2, 0], [0, 0, 0, 0, 0, 1, 0, 2, 1], [0, 0, 0, 0, 0, 1, 1, 0, 2], [0, 0, 0, 0, 0, 1, 1, 2, 0], [0, 0, 0, 0, 0, 1, 1, 2, 2], [0, 0, 0, 0, 0, 1, 2, 0, 0], [0, 0, 0, 0, 0, 1, 2, 0, 1], [0, 0, 0, 0, 0, 1, 2, 1, 0], [0, 0, 0, 0, 0, 1, 2, 1, 2], [0, 0, 0, 0, 0, 1, 2, 2, 1], [0, 0, 0, 0, 0, 2, 0, 0, 1], [0, 0, 0, 0, 0, 2, 0, 1, 0], [0, 0, 0, 0, 0, 2, 0, 1, 1], [0, 0, 0, 0, 0, 2, 1, 0, 0], [0, 0, 0, 0, 0, 2, 1, 0, 1], [0, 0, 0, 0, 0, 2, 1, 1, 0], [0, 0, 0, 0, 0, 2, 1, 1, 2], [0, 0, 0, 0, 0, 2, 1, 2, 1], [0, 0, 0, 0, 

Generación de la matriz de transición

In [36]:
matriz_transicion =  np.zeros((numero_estados_validos, 9), dtype=int)

for indice_estado, estado in enumerate(estados_posibles):
    for indice_accion in range(len(estado)):
        aux_estado = estado.copy()
        if aux_estado[indice_accion] in [1, 2]:
            matriz_transicion[indice_estado, indice_accion] = -1
        else:
            aux_estado[indice_accion] = 1
            if es_estado_valido(aux_estado) and not(es_victoria_jugador1(aux_estado) and es_victoria_jugador2(aux_estado)):
                matriz_transicion[indice_estado, indice_accion] = diccionaroInverso[numero_desde_estado(aux_estado)]
            else:
                aux_estado[indice_accion] = 2
                if es_estado_valido(aux_estado) and not(es_victoria_jugador1(aux_estado) and es_victoria_jugador2(aux_estado)):
                    matriz_transicion[indice_estado, indice_accion] = diccionaroInverso[numero_desde_estado(aux_estado)]
                else:
                    matriz_transicion[indice_estado, indice_accion] = -1


for fila in matriz_transicion:
    print(fila)

[2103  746  265   96   35   13    5    2    1]
[4154 1487  530  191   70   26   10    4   -1]
[4155 1488  531  192   71   27   11   -1    3]
[2105  748  267   98   37   15    7   -1   -1]
[2107  750  269  100   39   17    9   -1   -1]
[4157 1490  533  194   73   29   -1    8    6]
[2108  751  270  101   40   18   -1    7   -1]
[4160 1493  536  197   76   32   -1   -1   -1]
[2109  752  271  102   41   19   -1   -1    9]
[4161 1494  537  198   77   33   -1   -1   -1]
[2112  755  274  105   44   22   -1   12   -1]
[2113  756  275  106   45   23   -1   -1   12]
[4162 1495  538  199   78   34   -1   -1   -1]
[4163 1496  539  200   79   -1   21   16   14]
[2116  759  278  109   48   -1   18   15   -1]
[4166 1499  542  203   82   -1   24   -1   -1]
[2117  760  279  110   49   -1   19   -1   17]
[4167 1500  543  204   83   -1   25   -1   -1]
[4169 1502  545  206   85   -1   -1   20   -1]
[4171 1504  547  208   87   -1   -1   -1   20]
[2119  762  281  112   51   -1   -1   -1   -1]
[2120  763  2

Creación de la matriz Q

In [37]:
matriz_q = np.zeros((matriz_transicion.shape[0], matriz_transicion.shape[1]), dtype=float)
v = 0.9  # Factor de aprendizaje (learning rate)
y = 0.8  # Factor de descuento (discount factor)

s = 0
entrenar = 0
while entrenar < 1000000:
    a = np.random.randint(9)
    while matriz_transicion[s,a] == -1:
        a = np.random.randint(9)
    
    siguiente = matriz_transicion[s,a] 

    matriz_q[s, a] = (1 - v) * matriz_q[s, a] + v * (matriz_recompensas[siguiente] + y * max(matriz_q[siguiente,]))
    
    if matriz_recompensas[siguiente] != 0:
        s = 0
    else:
        s = siguiente
        
    entrenar += 1
    
    
for fila in matriz_q:
     print(fila)

[40.96 40.96 40.96 40.96 40.96 40.96 40.96 40.96 40.96]
[51.2 51.2 51.2 51.2 51.2 51.2 51.2 51.2  0. ]
[51.2 51.2 51.2 51.2 51.2 51.2 51.2  0.  51.2]
[40.96 64.   40.96 40.96 64.   40.96 40.96  0.    0.  ]
[64.   40.96 64.   40.96 64.   64.   40.96  0.    0.  ]
[51.2 51.2 51.2 51.2 51.2 51.2  0.  51.2 51.2]
[64.   40.96 64.   64.   64.   40.96  0.   40.96  0.  ]
[51.2 51.2 51.2 51.2 51.2 51.2  0.   0.   0. ]
[64.   40.96 64.   64.   64.   40.96  0.    0.   40.96]
[51.2 51.2 51.2 51.2 51.2 51.2  0.   0.   0. ]
[64.   40.96 64.   40.96 64.   64.    0.   40.96  0.  ]
[40.96 64.   40.96 40.96 64.   40.96  0.    0.   40.96]
[51.2 51.2 51.2 51.2 51.2 51.2  0.   0.   0. ]
[51.2 51.2 51.2 51.2 51.2  0.  51.2 51.2 51.2]
[40.96 40.96 40.96 64.   64.    0.   40.96 40.96  0.  ]
[51.2   51.2   51.2   51.2   32.768  0.    51.2    0.     0.   ]
[40.96 40.96 64.   64.   64.    0.   40.96  0.   64.  ]
[80.  80.  51.2 80.  80.   0.  80.   0.   0. ]
[51.2 51.2 51.2 51.2 51.2  0.   0.  51.2  0. ]
[51.2 51

Comprobación jugando partidas (SIN EMPEZAR)

In [38]:
partidas = 0
while partidas < 100:
    a = np.random.randint(9)
    while matriz_transicion[s,a] == -1:
        a = np.random.randint(9)
    partidas+=1